### ISSUE TITLE
Sky-Lab bot randomly disables machine

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#10]
**Describe the bug**
Sometimes the build skylab bot disables a machine

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BottingMarket** [comment]
I'll take a screenshot next time it happens

**Comment by berkeleyinc** [comment]
try if you still have that issue @BottingMarket
