### ISSUE TITLE
Issue with the new Reconnect System (Freezing on reconnect)

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#101]
**Describe the bug**
Bot succesfully reconnects but doesn't function after words it moves the ship to prevent timeout (Check Log)

**To Reproduce**
It happens rarely.

**Expected behavior**
Bot should go back to botting directly after succesfull reconnect.

**Screenshots**
![GolemZeus shot](https://user-images.githubusercontent.com/45576830/58438293-6e150380-80ce-11e9-8c47-54e2a1d23295.png)

**Additional context**
Log:
[GolemZeus.zip](https://github.com/berkeleyinc/Golem/files/3224910/GolemZeus.zip)

**Comment by BottingMarket** [comment]
I can confirm this still happens sometimes with the latest version (02-06-19).

**Comment by berkeleyinc** [comment]
Is the bot still on the map when that happens?

**Comment by berkeleyinc** [comment]
Also, the bot should try a relogin now if the reconnect button pressing didnt restore the connection.

**Comment by crashblaster** [comment]
Added more informations from users:
Describe the bug
Bot continue reconnect if autoreconnect is disabled.

To Reproduce
Deactivate Auto Reconnect in settings.
Log out and golem is automaticly relogin, when he should just log out

**Comment by crashblaster** [comment]
Should be fixed with Update 4.24.0
- Will relogin when reconnecting immediately didn't work a couple of times
