### ISSUE TITLE
Auto Galaxy Gate Generator bugged

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#102]
**Describe the bug**
Activate build up A/B/G on startup

**To Reproduce**
Activate Auto Galaxy Gate Generator

**Expected behavior**
Bot should buildup Gates with Extra Energie or what you selected.

**Log**
22:47:11 [info] GalaxyGate builder could not extract left samples.

**Comment by berkeleyinc** [comment]
Bot doesn't crash anymore

**Comment by crashblaster** [comment]
Still bugged:
16:38:48 [info] Starting GalaxyGate builder...
16:39:04 [info] Golem ready to operate.
16:39:04 [info] Changed bot mode -1->4
16:39:05 [info] Connected to the Gameserver.
16:39:10 [info] Connection successfully established.
16:39:10 [info] Map '3-1'. id=9, width=21000, height=13100, previous map: '-2'
16:39:11 [info] Worker ready
16:39:11 [info] Hero ship data found
16:39:11 [info] Requesting Rocket Precision Tech...
16:39:11 [info] Change to config 2 succeeded.
16:39:11 [info] Calculated path from 3-1 to 3-5: 3-2->3-4->4-3->4-4->3-5
16:39:16 [info] Building Rocket precision...
16:39:18 [warning] GalaxyGate builder could not extract left samples.
16:39:23 [info] Starting GalaxyGate builder...

**Comment by berkeleyinc** [comment]
should be fixed with the latest update
