### ISSUE TITLE
GG Bot: Zeta Gate, Bot keeps attacking Devourer

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#103]
**Describe the bug**
Bot is only attacking the devourer and cant clear the other NPC´s.

**To Reproduce**
Start Zeta Gate. Wait until the first Wave is done >> Bot keeps attacking Devourer and isn´t switching back to the other NPC´s

**Expected behavior**
Bot should only attack Devourer if there are no other NPC´s arround.

![devourer](https://user-images.githubusercontent.com/48995248/58813950-212cb200-8625-11e9-86e4-e9a271678977.png)

*Screen from Botting-Market

**Comment by berkeleyinc** [comment]
fixed in 4.24

**Comment by crashblaster** [comment]
bug happens again

**Comment by BottingMarket** [comment]
Fixed
