### ISSUE TITLE
Bot doesn´t attack registered opponents (NPC list)

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#104]
**describe:** 
NPC ships named in ship list are not in ship list

**to reproduce:**
go to X-5, select Lordakium, Lordakia, Lordakium Spor, Sibelonit and Boss Sibelonit in your ship list and wait

**expected:**
a ship in shiplist gets attacked.

screen:
![Shiplist](https://user-images.githubusercontent.com/48995248/58819493-a8335780-8630-11e9-9a8a-5253dc62c08a.png)

**Comment by berkeleyinc** [comment]
I can't reproduce that. reopen if it happens to you

**Comment by crashblaster** [comment]
![image](https://user-images.githubusercontent.com/48995248/58885946-5e577980-86e3-11e9-9de2-fade6bcde192.png)

**Comment by crashblaster** [comment]
16:15:26 [info] Select '-=[ Sibelonit ]=-' (150201086).
16:15:26 [warning] Can't find currently selected ship in ships list.
16:15:26 [info] Select '-=[ Sibelonit ]=-' (150201086).
16:15:26 [warning] Can't find currently selected ship in ships list.
16:15:26 [info] Select '-=[ Sibelonit ]=-' (150201086).
16:15:26 [warning] Can't find currently selected ship in ships list.
16:15:26 [info] Select '-=[ Sibelonit ]=-' (150201086).
16:15:26 [warning] Can't find currently selected ship in ships list.
16:15:26 [info] Select '-=[ Sibelonit ]=-' (150201086).
16:15:26 [warning] Can't find currently selected ship in ships list.
16:15:26 [info] Select '-=[ Sibelonit ]=-' (150201086).
16:15:26 [info] Attack '-=[ Sibelonit ]=-' (100% hpt).
16:15:27 [info] Select '-=[ Sibelonit ]=-' (150200056).
16:15:27 [info] Attack '-=[ Sibelonit ]=-' (100% hpt).
16:15:27 [info] Attack '-=[ Sibelonit ]=-' (100% hpt).
16:15:32 [info] Collecting box type 2

Because of this issue he is random switching enemies.

**Comment by crashblaster** [comment]
Still happens:
19:22:05 [info] Select '* Lordakium Spore *' (150200771).
19:22:05 [info] Select '* Lordakium Spore *' (150200771).
19:22:05 [warning] Can't find currently selected ship in ships list.
19:22:05 [info] Select '* Lordakium Spore *' (150200771).
19:22:06 [info] Attack '* Lordakium Spore *' (100% hpt).
19:22:06 [info] NPC '* Lordakium Spore *' killed.

**Comment by BottingMarket** [comment]
Still a problem as of 2019 July 16

**Comment by berkeleyinc** [comment]
This happens only on X-5?

**Comment by BottingMarket** [comment]
All maps with specific npc in the list

Op wo 17 jul. 2019 17:29 schreef berkeleyinc <notifications@github.com>:

**Comment by crashblaster** [comment]
since the last updates: very sporadic
In one hour botting 15x times.
