### ISSUE TITLE
Bot fleeing to x-3 (Group Gate) 

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#105]
**Describe the bug**
Bot on x-2.

**To Reproduce**
Bot fleeing random on x-2 gate to x-3 >> then flying to group gate, and waiting there.

**Expected behavior**
Bot shouldnt flee to the group gate and continue normally.

**Screenshots, Video**
https://www.youtube.com/watch?v=Y6324z_XtJE&feature=youtu.be

**Additional context**

**Comment by berkeleyinc** [comment]
where is that x-3 gate that the bot should ignore?

**Comment by crashblaster** [comment]
on 1-3 and 2-3 it´s in the upper left corner. On 3-3 it´s in the upper right corner.

**Comment by crashblaster** [comment]
Closed for now, they guy who reported this issue isn´t responding my questions and deleted the video.
