### ISSUE TITLE
PET Autoloot doesn´t work permanently

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#107]
**Describe the bug**
The autoloot doesnt work properly, after a time golem switched back to guard mode even tho its set not to do so and you have to set it back manually.

**To Reproduce**
Use autoloot and wait some time

**Expected behavior**
That golem doesnt ignore its settings and uses autoloot and not randomly switches back to guard mode for no reason

**Comment by BottingMarket** [comment]
Still a problem as of update 2019 July 16

**Comment by crashblaster** [comment]
Seems fixed. Not reproducible

**Comment by crashblaster** [comment]
Seems fixed. Not reproducible
