### ISSUE TITLE
New ammo key feature is responsible for the NPC change

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#111]
**Describe the bug**
18:03:55 [info] Pressing ammo key 1
18:03:55 [info] Select '..::{ Boss StreuneR }::..' (150200372).
18:03:56 [info] Roaming map ...
18:04:01 [info] Pressing ammo key 1
18:04:01 [info] Select '-=[ StreuneR ]=-' (150200310).
18:04:02 [info] Pressing ammo key 1
18:04:02 [info] Select '-=[ StreuneR ]=-' (150200310).
18:04:02 [info] Attack '-=[ StreuneR ]=-' (100% hpt).
18:04:07 [info] Going to shoot range...
18:04:09 [info] NPC '-=[ StreuneR ]=-' killed.
18:04:09 [info] Pressing ammo key 1
18:04:09 [info] Select '-=[ StreuneR ]=-' (150200345).
18:04:09 [info] Pressing ammo key 1
18:04:09 [info] Select '-=[ StreuneR ]=-' (150200345).
18:04:09 [info] Earned 12000 Cre. (total 31110700)
18:04:09 [info] Earned 15 Uri. (total 25633)
18:04:10 [info] Pressing ammo key 1
18:04:10 [info] Select '-=[ StreuneR ]=-' (150200844).
18:04:10 [info] Pressing ammo key 1
18:04:10 [info] Select '-=[ StreuneR ]=-' (150200844).
18:04:10 [info] Attack '-=[ StreuneR ]=-' (100% hpt).
18:04:16 [info] Going to shoot range...
18:04:17 [info] NPC '-=[ StreuneR ]=-' killed.

**To Reproduce**
Setup ammo key on an NPC. Start botting. Bot starts attacking via ammo key but when after bot tries to start his own attack via internal function and this stops the currend attack.

**Expected behavior**
Bot should work like this with setted ammo key:

Select NPC Streuner
Attack NPC Streuner via ammo key 1
>> Killed >> Roaming or selecting next one

If ammo key isnt setup or there are no NPC´s on the list. The bot should use the internal function:
Select NPC Streuner
Attack NPC Streuner via STRG Pressing STRG
>> killed >> Roaming or selecting next one

**Comment by BottingMarket** [comment]
Should be fixed workaround added by INk

**Comment by crashblaster** [comment]
Still bugged

**Comment by crashblaster** [comment]
Fixed
Update v4.27.2 
- DO: fix change target when using Ammo key
