### ISSUE TITLE
GG bot autojump next gg doesn't work

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#112]
**Describe the bug**
When 1 gate has been completed and the bot jumps to x-1 map it will not jump into the next GG even when it's on the map (Tested with abg and zeta).

**To Reproduce**
Activate GG bot when 2 or more gates are on map.

**Expected behavior**
Bot should restart after every gate and check every x seconds if there are new gates on the map to jump to.

**Screenshots**
![GolemThomas shot](https://user-images.githubusercontent.com/45576830/61380442-ac969580-a8a9-11e9-80fb-44f297cfba88.png)

**Additional context**
22:15:03 [trace] BB2018 BB1078 DOB1218 tick=127
22:15:08 [trace] Send keys: 0
22:15:08 [trace] BB2018 BB1078 DOB1218 tick=47
22:15:13 [trace] BB2018 BB1078 DOB1218 tick=31
22:15:18 [trace] Send keys: 0
22:15:18 [trace] BB2018 BB1078 DOB1218 tick=16
22:15:23 [trace] BB2018 BB1078 DOB1218 tick=48
22:15:28 [trace] Send keys: 0
22:15:29 [trace] BB2018 BB1078 DOB1218 tick=29
22:15:34 [trace] BB2018 BB1078 DOB1218 tick=17
22:15:37 [debug] Ping status server
22:15:38 [trace] Send keys: 0
22:15:38 [error] Connection to status server lost.
22:15:39 [trace] BB2018 BB1078 DOB1218 tick=51
22:15:44 [trace] BB2018 BB1078 DOB1218 tick=14
22:15:48 [trace] Send keys: 0
22:15:49 [trace] BB2018 BB1078 DOB1218 tick=15
22:15:54 [trace] BB2018 BB1078 DOB1218 tick=100
22:15:58 [trace] Send keys: 0
22:15:59 [trace] BB2018 BB1078 DOB1218 tick=14
22:16:04 [trace] BB2018 BB1078 DOB1218 tick=14
22:16:08 [trace] Send keys: 0
22:16:09 [trace] BB2018 BB1078 DOB1218 tick=117
22:16:14 [trace] BB2018 BB1078 DOB1218 tick=85
22:16:18 [trace] Send keys: 0
22:16:19 [trace] BB2018 BB1078 DOB1218 tick=35
22:16:24 [trace] BB2018 BB1078 DOB1218 tick=30
22:16:28 [trace] Send keys: 0

**Comment by berkeleyinc** [comment]
I just testedt it and it worked.
I need the full log in case it happens again
