### ISSUE TITLE
GG Bot doesn't restart after a gate has been done

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#113]
**Describe the bug**
GG Bot doesn't restart after a gate has been done

**To Reproduce**
Start gg bot when 2 gates are on map.

**Expected behavior**
Bot should restart after a gate has been complete in order to clear memory (High memory results in bad tick interval).

**Screenshots**
No Screen needed.

**Additional context**
Golem log:
[GolemThomas.log](https://github.com/berkeleyinc/Golem/files/3402198/GolemThomas.log)

**Comment by berkeleyinc** [comment]
the bot only restarts if it had been running for an hour already
