### ISSUE TITLE
GG Protegit wave improvement

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#114]
**Describe the bug**
No bug but I have a workaround to improve the Protegit waves.

**To Reproduce**
-

**Expected behavior**
Alright in order to improve the protegit wave, the tick rate should be low as possible that is being achieved by having the ram memory at it's lowest.
When the bot is done with the Kristallon wave in ABG it should do a restart before jumping to the Protegit wave.

**Screenshots**
-

**Additional context**
Needs to restart here:
15:48:14 [info] Attack '-=[ Kristallon ]=- α36' (19% hpt).
15:48:18 [info] Select '-=[ Kristallon ]=- α36' (150200735).
15:48:18 [info] Attack '-=[ Kristallon ]=- α36' (5% hpt).
15:48:19 [info] NPC '-=[ Kristallon ]=- α36' killed.
15:48:19 [info] Jumping to next wave...

**Comment by berkeleyinc** [comment]
Will do that in the latest update now
