### ISSUE TITLE
Display bug of uri/h

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#12]
**Describe the bug**
There is a bug with Uri/h (Didnt check if it does it with cred/h too)

**To Reproduce**
But for exemple i'm at 5k5/h , And when i click "Stop" it just go to the half , Now it shows that with 2.3k uri in 25mins , I'm doing 2.7k/h

**Comment by berkeleyinc** [comment]
fixed in x.12.5
