### ISSUE TITLE
Attack not successful

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#123]
### User report from discord
**Describe the bug**
the bot does not attack npcs
he shot 1 time
and still ignoring that npc

**To Reproduce**
use NPC Killer

**Expected behavior**
bot should attack the selected NPC

**Screenshots/Log**
14:27:27 [warning] Could not attack '( UberStreuneR )'.
14:27:27 [warning] Attack not successful (2).
14:27:27 [info] Attack '( UberStreuneR )' (99% hpt).
14:27:28 [warning] Attack not successful (1).
14:27:28 [warning] Could not attack '( UberStreuneR )'.
14:27:28 [warning] Attack not successful (1).
14:27:28 [warning] Could not attack '( UberStreuneR )'.
14:27:28 [warning] Attack not successful (1).
14:27:28 [warning] Could not attack '( UberStreuneR )'.
14:27:28 [warning] Attack not successful (1).
14:27:28 [warning] Could not attack '( UberStreuneR )'.
14:27:28 [warning] Attack not successful (1).
14:27:28 [warning] Could not attack '( UberStreuneR )'.
14:27:28 [warning] Attack not successful (1).
14:27:28 [warning] Could not attack '( UberStreuneR )'.
14:27:28 [warning] Attack not successful (1).
14:27:28 [warning] Could not attack '( UberStreuneR )'.

**Additional context**

**Comment by berkeleyinc** [comment]
fall-back attack type get activated when that happens
