### ISSUE TITLE
Boss StreuneR ability

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#13]
**Describe the bug**
when the ship has boss streuner's or boss saimon's ability on and the bot see an enemy it won't flee and stay there

**Screenshots**
https://cdn.discordapp.com/attachments/434346843447492628/519522622526980106/bug.png

**Additional context**
Log:
https://cdn.discordapp.com/attachments/434346843447492628/519522726223020083/Golem_log.txt

**Comment by BottingMarket** [comment]
Seems to be fixed closing
