### ISSUE TITLE
OSR Startup Bug

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#14]
**Describe the bug**
Sometimes when starting the OSR mode it never logs in, see screenshot for the problem

**To Reproduce**
Run OSR mode 10 times it never logs in 2/10 times

**Expected behavior**
Login doesn't get triggered?

**Screenshots**
![desktop screenshot 2018 12 05 - 00 06 10 48](https://user-images.githubusercontent.com/45576830/49479017-dec71b80-f821-11e8-91db-a565eccbc79c.png)

**Additional context**
Nothing

**Comment by BottingMarket** [comment]
The Strange thing is when logging all together it doesn't happen and if I log them one by one some get stuck

**Comment by berkeleyinc** [comment]
seems to be fixed
