### ISSUE TITLE
New BL Maps

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#16]
**Describe the bug**
If he flees from an enemy and jumps onto the BL Map then he stops and doesn't jump back any more

**Screenshots**
http://prntscr.com/lr9c34

**Comment by BottingMarket** [comment]
It's best to not work on the BL maps the maps are not bot friendly and not worth it

**Comment by berkeleyinc** [comment]
new maps added with vX.13.1
