### ISSUE TITLE
Bot is not reviving the Ship

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#17]
**Describe the bug**
When Killed it won't revive at gate or at base

**To Reproduce**
Get ship killed and use OSR Mode

**Expected behavior**
Bot should revive ship

**Screenshots**
![golem jongkomklappen shot](https://user-images.githubusercontent.com/45576830/49571436-8e42e180-f939-11e8-9a71-448d7b18480b.png)
![golem jos shot](https://user-images.githubusercontent.com/45576830/49571437-8edb7800-f939-11e8-8745-df814cfe95d9.png)
![golem killerstef shot](https://user-images.githubusercontent.com/45576830/49571438-8edb7800-f939-11e8-99fc-bd2035ef68cf.png)
![golem lostplanet shot](https://user-images.githubusercontent.com/45576830/49571439-8edb7800-f939-11e8-8f61-19378fd91f7a.png)
![golem sid shot](https://user-images.githubusercontent.com/45576830/49571817-94858d80-f93a-11e8-9ad1-0ba236a202fa.png)

**Additional context**
Here are the logs:
[Golem JongKomKlappen.log](https://github.com/berkeleyinc/Golem/files/2652265/Golem.JongKomKlappen.log)
[Golem Jos.log](https://github.com/berkeleyinc/Golem/files/2652266/Golem.Jos.log)
[Golem KillerStef.log](https://github.com/berkeleyinc/Golem/files/2652267/Golem.KillerStef.log)
[Golem LostPlanet.log](https://github.com/berkeleyinc/Golem/files/2652268/Golem.LostPlanet.log)
[Golem Willem.log](https://github.com/berkeleyinc/Golem/files/2652269/Golem.Willem.log)
[Golem Sid.log](https://github.com/berkeleyinc/Golem/files/2652287/Golem.Sid.log)

**Comment by berkeleyinc** [comment]
fixed
