### ISSUE TITLE
Crash of Process (Take a look at the log)

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#18]
**Describe the bug**
He was killing npc and then it stopped working

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
[Golem Willem.log](https://github.com/berkeleyinc/Golem/files/2652772/Golem.Willem.log)

**Comment by berkeleyinc** [comment]
The log isn't saying anything helpful. Not sure why that happens

**Comment by berkeleyinc** [comment]
Did that happen again?

**Comment by BottingMarket** [comment]
seems to be fixed closing
