### ISSUE TITLE
CBS Box problem

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#22]
**Describe the bug**
When a bonus box is near an enemy CBS and you have "Avoid clan Bases" ticked, the bot will try to collect the box but then recognize the CBS and fly away from it. But then he sees the box and want to collect it which ends in a constantly loop of fleeing and then try again to collect it. 

**To Reproduce**
Fly near a Enemy CBS witch "Avoid clan Bases" Ticked, if there are no NPCs near (or you are only collecting boxes) you should see it. 

**Expected behavior**
I would expect that the bot Ignore boxes near an enemy CBS completly.

**Screenshots**
https://i.gyazo.com/3d90d6e13f7ddc375351cd5e1e800255.mp4

**Comment by berkeleyinc** [comment]
fixed in 3.14.2
