### ISSUE TITLE
Faster Treasure Collecting

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#23]
**Describe the bug**
It's no bug but in darkorbit when collecting a booty box/treasure it stands on the box for aound 7 seconds while it only takes 5 seconds~ to collect, could the time be faster?

**To Reproduce**
Collect Treasures in Darkorbit

**Expected behavior**
When the booty box is collected go straight away for next boxes

**Screenshots**
![desktop screenshot 2018 12 07 - 15 56 43 82](https://user-images.githubusercontent.com/45576830/49654654-bb29ee00-fa38-11e8-9e8e-84cda06ed674.png)

**Additional context**
Nothing.

**Comment by berkeleyinc** [comment]
fixed
