### ISSUE TITLE
GG Bot flying out of map in raditation Zone

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#31]
**Describe the bug**
When GG bot is activated bot flies out of map into the radiation zone

**To Reproduce**
Activate GG bot in a gate

**Expected behavior**
Bot should stay close to the NPC so he shoots the npc all the time and avoid the radiation zone

**Screenshots**
Not needed

**Additional context**

**Comment by iNSOMNiA3D** [comment]
He doesn't do that to me.
