### ISSUE TITLE
Bot stops attacking check log

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#34]
**Describe the bug**
When in NPC killer mode sometimes the bot stops attacking, the logs says that it's pressing ctr but it won't attack

**To Reproduce**
Run NPC killer and check if it happens most of the times around 1 hour

**Expected behavior**
The bot should always shoot npc's

**Screenshots**

**Additional context**
[Golem Jos.log](https://github.com/berkeleyinc/Golem/files/2687713/Golem.Jos.log)

**Comment by berkeleyinc** [comment]
Please reproduce with the GUI version and press CTRL on your own when that happens and tell me what happens

**Comment by berkeleyinc** [comment]
fixed
