### ISSUE TITLE
GG Builder Wasting Uridium

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#35]
**Describe the bug**
Not a bug but more of a important improvement: 
Once a gate has all part, It's not putting it on map.
Also when a gate is ready and all the piece to build the other is ready,
The bot continue to build the other Gates .Which is a waste of Uridium
Founded by Reflector

**To Reproduce**
Use GG Builder

**Expected behavior**
GG Builder should place the gates directly on the map.

**Screenshots**
None

**Additional context**
Nothing

**Comment by iNSOMNiA3D** [comment]
if there is a gate, he should not click on it but first do the gate
