### ISSUE TITLE
Add Ammo change on each npc

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#37]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
he should recognize which npc he shoots and select the ammo I have set to it

**Additional context**
i take Vertex as an example
![laser key setup](https://user-images.githubusercontent.com/45575296/50330513-cf232480-04fb-11e9-87c8-1c4e0277c267.png)
![ammo change](https://user-images.githubusercontent.com/45575296/50330516-d2b6ab80-04fb-11e9-8b41-0ee4ef3b57e4.png)

**Comment by berkeleyinc** [comment]
added via ammo key
