### ISSUE TITLE
Using NOGUI has no icon in taskbar

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#39]
**Describe the bug**
When NOGUI is enabled it has no icon in taskbar.

**To Reproduce**
Use nogui

**Expected behavior**
It should have the golem icon in taskbar.

**Screenshots**
![capture](https://user-images.githubusercontent.com/45576830/50330217-b23a2180-04fa-11e9-92cc-3e0b7fe34589.PNG)
It should have this icon:
![knipsel](https://user-images.githubusercontent.com/45576830/50330268-d85fc180-04fa-11e9-97d4-6221d7ee8fbc.JPG)

**Additional context**
None

**Comment by berkeleyinc** [comment]
it's not a bug. The icon in the taskbar is part of the GUI and therefore no icon when noGui is activated
