### ISSUE TITLE
GG Bot fly up Range

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#40]
**Describe the bug**
If he fly up he dont shoot

**Screenshots**
![fly up range](https://user-images.githubusercontent.com/45575296/50330406-5623cd00-04fb-11e9-91b9-1c555c00a9ff.png)
![fly up](https://user-images.githubusercontent.com/45575296/50331203-2a561680-04fe-11e9-9a9a-756870558cdf.gif)

**Comment by BottingMarket** [comment]
#41 Oval movement would fix this ^^

**Comment by iNSOMNiA3D** [comment]
> 
> 
> #41 Oval movement would fix this ^^

i think that too

**Comment by berkeleyinc** [comment]
You can see in the log that the bot can't select the NPCs. Simply changing your window dimensions or zoom (in 2D) would fix that.
