### ISSUE TITLE
GG Oval movement

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#41]
**Is your feature request related to a problem? Please describe.**
Yes, GG Range Problem.

**Describe the solution you'd like**
If the Bot Oval would fly, the range problem would be solved.

**Additional context**
![gg oval movement](https://user-images.githubusercontent.com/45575296/50331077-bc115400-04fd-11e9-8bf4-6eb4e9dc55f2.png)

**Comment by berkeleyinc** [comment]
The bot is already moving oval but we can make it even more oval
