### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#5]
**Is your feature request related to a problem? Please describe.**
No but OSR Client needs some updates 

**Additional context**
OSR - Improve overall performance of the OSR client (Faster npc killing, collecting etc.)

**Comment by BottingMarket** [comment]
Think that the bot selects them fast but doesn't shoot them fast

**Comment by berkeleyinc** [comment]
Try with the new version if you still have that problem

**Comment by BottingMarket** [comment]
Seems like performance is better with new version also the zoom function helps alot with selecting the npc's fast

**Comment by BottingMarket** [comment]
Performance is much better closing
