### ISSUE TITLE
GG bot Boss Lordakiums Corner mode to much range

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#51]
**Describe the bug**
When the bot activates corner mode on Boss Lordarkiums it will never get into range.

**To Reproduce**
Do Lambda or Kappa gate with Boss Lordakiums.

**Expected behavior**

**Screenshots**
![desktop screenshot 2018 12 22 - 11 15 46 87](https://user-images.githubusercontent.com/45576830/50373445-a4120100-05df-11e9-88cb-d2ef092848d9.png)

**Additional context**
If you fix this bug then you can add Lambda and Kappa gate to the list that the GG bot can do.

**Comment by berkeleyinc** [comment]
fixed with v4.18.3
