### ISSUE TITLE
Process PPapi and Cannot get stage dimensions

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#52]
**Describe the bug**
Process PPapi gets unstable when Tick Rate goes to high and also "Cannot get Stage Dimensions" happens.

**To Reproduce**
When logged in go to home and press galaxy gate the tick rate will skyrocket for 1 sec and it will get unstable and crash.

**Expected behavior**
The bot shouldn't stop/crash when tickrate gets to high.

**Screenshots**
![desktop screenshot 2018 12 22 - 11 42 03 29](https://user-images.githubusercontent.com/45576830/50373545-03bcdc00-05e1-11e9-84b1-2bff53e3d0ff.png)

**Additional context**
-

**Comment by iNSOMNiA3D** [comment]
I get that, too.

**Comment by crashblaster** [comment]
Cannot get stage dimensions still happens sometimes

**Comment by crashblaster** [comment]
The bot logs "Cannot get Stage Dimensions". Is it possible that the bot automatically restart after this error?

**Comment by crashblaster** [comment]
It just happens when you use - Home. It happens because of flashplayer just on Hangar or Galaxy Gates. In Skylab i cant reproduce this issue.

**Comment by crashblaster** [comment]
Bot is automatically restarting when this issue happens. As long as there is no better solution, it is currently solved. Closed
