### ISSUE TITLE
GG Gamma Sibelons corner range

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#53]
**Describe the bug**
right uper corner and left lower corner Sibelons not in Range
DontAdaptGGDistance: true
use builtin distance: true

**Screenshots**
![lower corner range to low](https://user-images.githubusercontent.com/45575296/50374342-ec83eb80-05ec-11e9-9b63-721ce72166ea.gif)

**Comment by BottingMarket** [comment]
Fixed
