### ISSUE TITLE
GG Issue with option AlwaysUseMinimap

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#54]
**Describe the bug**
In the Beta gate he activates the corner mode but gets stuck in the middle of the map far under (Check screenshot).
Also check Golem.log seems that the bot had some long breaks between some gates.

**To Reproduce**
Do some ABG gates.

**Expected behavior**
To go to the right corner instead of getting stuck in the middle of the map.

**Screenshots**
![golem shot](https://user-images.githubusercontent.com/45576830/53986107-97507400-411d-11e9-966f-6245c8ba383c.png)
![golem coordinates were ship gets stuck](https://user-images.githubusercontent.com/45576830/53986113-99b2ce00-411d-11e9-8ed6-14ab59ba7dd3.png)
[Golem.log](https://github.com/berkeleyinc/Golem/files/2943112/Golem.log)

**Additional context**
Summary:
-Bot gets stucks in GG (Corner mode)
-Add Relogin/Restart gate completed

**Comment by berkeleyinc** [comment]
Happens due to activated AlwaysUseMinimap option
