### ISSUE TITLE
Reached internal deadline 2 Crash

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#56]
**Describe the bug**
When logging in the Flash client stops responding resulting in a crash

**To Reproduce**
Login a lot of times it happens 1/10 times

**Expected behavior**
That it doesn't stop responding

**Screenshots**
-

**Additional context**
I suggest fixing the Relogin function maybe that will help it

**Comment by crashblaster** [comment]
That only happens when you switch on -Home or?
I were able to fix this by starting darkorbit in my webbrowser (chrome) before starting the bot. I accepted in chrome to use the flash player. After this i have no Problems with Flash. Maybe this helps you.

**Comment by BottingMarket** [comment]
Nope it happens rarely nowadays it's only on starting the bot I only use OSR and NOGUI mode

**Comment by berkeleyinc** [comment]
This happens due to the Flash Player freezing. We need to figure out, how to reproduce it properly

**Comment by BottingMarket** [comment]
[Golem Baker.log](https://github.com/berkeleyinc/Golem/files/3024479/Golem.Baker.log)
Another Crash.
I suggest when this happens: 21:31:08 [warning] Waiting for 3 minutes already.. Stop loading.
Run the Taskkill and Restart the bot instead of stop Loading.
