### ISSUE TITLE
Not using Flee Config 2 when fleeing because of low HP/Shield

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#59]
**Describe the bug**
Bot is fleeing to near gate beaucse of low HP/Shield. Bot pressing Flee Button(s) but he is not switching to flee Config 2. After jumping on other map he is switching to Config 2 >> Thats too late.

**To Reproduce**
Steps to reproduce the behavior: Getting shot by Aliens/Friends on lower HP/Shield then selected>> Bot has to repair.

**Expected behavior**
Bot should switch to Config 2 while fleeing to repair.

**Comment by crashblaster** [comment]
BottingMarket missclicked

**Comment by berkeleyinc** [comment]
4.18.8 will do that

**Comment by crashblaster** [comment]
tested and it works
