### ISSUE TITLE
Bot shouldn´t collect Bonus Boxes when NPC is under 40% HP while killing NPC

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#60]
**Is your feature request related to a problem? Please describe.**
Bot isnt finishing the NPC kill when he collects the Bonus-Box and the NPC is fleeing because of Low HP. That only happens when you have activated "Simultaneously collect boxes and shoot NPC´s"

**Describe the solution you'd like**
When the attacked NPC is under 40% HP the bot shouldn´t collect bonus boxes even if simultaneouly is activated.

I know i can set the shooting timeout longer or activate only collect when no npcs around. But i think my solution is not to difficult and saves us time and makes it more effective to kill npc´s and collect at the same time.

**Comment by berkeleyinc** [comment]
Added with v4.18.3

**Comment by crashblaster** [comment]
That was fast :dancer:
