### ISSUE TITLE
Bot Flee to X-8 Map base

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#61]
**Is your feature request related to a problem? Please describe.**
It would be great if the bot would see the X-8 base as a safe zone. So when it's close it will also flee to the base, instead fleeing to a Base that's much further away.

**Describe the solution you'd like**
Also flee to X-8 Base.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by berkeleyinc** [comment]
Duplicate of https://github.com/berkeleyinc/Golem/issues/7
