### ISSUE TITLE
Improve Fleeing of the Bot when Near Safe Zone

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#62]
**Is your feature request related to a problem? Please describe.**
The problem is that the bot keeps jumping a gate even when it's in the safe zone.

**Describe the solution you'd like**
When the bot is on a safe zone (Gate) and a enemy is near don't keep jumping wait for the enemy to go away and return to botting.

**Describe alternatives you've considered**
-

**Additional context**
Example of a Safe zone:
![Desktop Screenshot 2019 03 29 - 15 05 08 03](https://user-images.githubusercontent.com/45576830/55238181-268c0b80-5234-11e9-8b58-c61988a4d191.png)

**Comment by crashblaster** [comment]
Added with:
Update v4.21.7
- Small stability fix
- DO: Will wait 3 secs between AfterFlee button / Flee button presses
- DO: Press afterFlee button upon start
**- DO: reognize NAZ to prevent unnecessary jumps**
