### ISSUE TITLE
Darkorbit Attack bugs out.

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#64]
**Describe the bug**
It happens when the bot attacks a NPC accidently that's not in the npc killer list.

**To Reproduce**
Hard to reproduce. But have the bot attack a NPC that's not in the list.

**Expected behavior**
The bot should not attack the NPC and if it does accidently it shouldn't stay locked.

**Screenshots**
The bot is attacking the Boss Devolarium (not in the list) it keeps it locked.
![Golem Destro shot](https://user-images.githubusercontent.com/45576830/55245016-9903e800-5242-11e9-8253-9aea3a5acbdb.png)

**Additional context**
Added Log It happens at the end of the log when it said: [warning] Selected target shouldn't be attacked for now.
[Golem Destro.log](https://github.com/berkeleyinc/Golem/files/3023411/Golem.Destro.log)

**Comment by berkeleyinc** [comment]
related to https://github.com/berkeleyinc/Golem/issues/65
