### ISSUE TITLE
Bot doesn't attack CTRL doesn't register

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#65]
**Describe the bug**
After some time the bot just bugs out not shooting at all

**To Reproduce**
Have NPC killer on and wait a long time

**Expected behavior**
Bot should attack with CTRL.

**Screenshots**
Bot has locked the npc and log is saying that it's attacking but it's not
![Golem Eves shot](https://user-images.githubusercontent.com/45576830/55250863-7a581e00-524f-11e9-88ce-41e7a14d9372.png)

**Additional context**
Added Log
[Golem Eves.log](https://github.com/berkeleyinc/Golem/files/3023753/Golem.Eves.log)

**Comment by berkeleyinc** [comment]
should be fixed now. Reopen if you still have the problem

**Comment by BottingMarket** [comment]
[Golem Lok.log](https://github.com/berkeleyinc/Golem/files/3024418/Golem.Lok.log)
![Golem Lok shot](https://user-images.githubusercontent.com/45576830/55260657-412ca780-5269-11e9-8605-3943600e3a42.png)
Bug still persist I think it only happens on OSR mode

**Comment by crashblaster** [comment]
I don´t use OSR mode and i dont have this bug.

**Comment by BottingMarket** [comment]
Fixed
