### ISSUE TITLE
Darkorbit Selected wrong target, now continueing with that one.. Bug

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#67]
**Describe the bug**
Bot attacks NPC's Very late it does not register CTRL properly

**To Reproduce**
Activate NPC killer with Debug mode on etc.

**Expected behavior**
Bot should directly attack and not display: Selected wrong target, now continueing with that one..

**Screenshots**
[Golem Attack Bug v4.0.18.6-1.zip](https://github.com/berkeleyinc/Golem/files/3045399/Golem.Attack.Bug.v4.0.18.6-1.zip)

**Additional context**
22:29:02 [warning] Selected wrong target, now continueing with that one..
22:29:02 [info] Attack '-=[ Streuner ]=- κ1'.
22:29:02 [trace] Deselecting target.
22:29:03 [warning] Selected wrong target, now continueing with that one..
22:29:03 [info] Attack '-=[ Streuner ]=- κ1'.
22:29:03 [trace] Deselecting target.
22:29:03 [warning] Selected wrong target, now continueing with that one..
22:29:03 [info] Attack '-=[ Streuner ]=- κ1'.
22:29:03 [trace] Deselecting target.
22:29:03 [warning] Selected wrong target, now continueing with that one..
22:29:03 [info] Attack '-=[ Streuner ]=- κ1'.
22:29:03 [trace] Deselecting target.
22:29:03 [warning] Selected wrong target, now continueing with that one..
22:29:03 [info] Attack '-=[ Streuner ]=- κ1'.
22:29:04 [trace] Deselecting target.
22:29:04 [warning] Selected wrong target, now continueing with that one..
22:29:04 [info] Attack '-=[ Streuner ]=- κ1'.
22:29:04 [trace] Deselecting target.

**Comment by BottingMarket** [comment]
Should be fixed ASAP

**Comment by crashblaster** [comment]
I fixed it for now by deactivating >> Only shoot full hp npc´s
It is not the solution but a temporary  alternative.

**Comment by berkeleyinc** [comment]
check if you still have that problem

**Comment by BottingMarket** [comment]
Fixed
