### ISSUE TITLE
GG Getting Damage from Kristallon´s

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#68]
**Describe the bug** (i tested in Gamma Gate)
Getting Damage from Kristallon´s. Bot has to repair after a few seconds. Bot is not dealing much Damage to the Kristallons so it takes a lot of time to do this wave. Sometimes he stucks while repairing and he gets more damage. Then the Bot flees in the last seconds and has to repair again. When every kirstallon is low in the corner, the bot is correctly killing them.

**To Reproduce**
Start GG Bot wait until Kristallon Wave. Using Reparing while circling.

**Expected behavior**
Just getting Damage when there is a Lagg. Not stucking while repairing. It costs much more time.

**Screenshots**
No Screens at the time. I will add them.

**Comment by berkeleyinc** [comment]
4.18.8 has a higher range for Kristallons
