### ISSUE TITLE
X-8 Base as save point

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#7]
**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
The base could be handled just like the portal with more range but just leave out the jumping

**Additional context**
If he has little life then he flies with life to the gate. He should already stay at the base. If an enemy comes he should flee to base as well.

**Comment by KickMayer** [comment]
Hm, should repair to % set in the settings and then fly to the workmaps portal. No? :P

**Comment by iNSOMNiA3D** [comment]
> 
> 
> Hm, should repair to % set in the settings and then fly to the workmaps portal. No? :P

no unfortunately not he does not recognize the base that is when he sees an enemy he flees directly to the gate with low life
