### ISSUE TITLE
Bot not using Flee Config 2, to get faster on Work-Map

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#70]
**Describe the bug**
When the Bot is flying on his workmap, he is not using the Flee Config 2. he is just pressing Flee Buttons.

**To Reproduce**
Start on another map then the workmap.

**Expected behavior**
Bot should use Flee Config 2 to get faster on workmap. 
Improvement of efficiency

**Comment by berkeleyinc** [comment]
You probably have restoreShieldBeforeConfigChange activated

**Comment by crashblaster** [comment]
> You probably have restoreShieldBeforeConfigChange activated

Yes i have. I noticed that he is switching after restoring full shield. But there is a little problem on x-8. The streuners attack with rockets, so the ship stops repairing. Maybe the bot should wait in base and restore full shield/hp and after that he can starts flying to workmap. Maybe we can activate it with a button. Because some people bon on x-2/x-3/x-4. There the ship can repair while flying on x-1 to x-2.

**Comment by berkeleyinc** [comment]
with the next Version, the bot will use the flee config to get to the workMap
