### ISSUE TITLE
Bot stucks on 4-4 after fleed from enemie on x-5 succesfully

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#71]
Added from a report in Discord:
describe:
when bot flees on x-5 maps it flees to 4-4 and then gets stucked

**Botting on x-5 not possible at the moment if you use revive at gate. Bot jumps on 4-4 and dies there until the death limit is reached. Bot never jumped back from 4-4 to x-5. Just with Revive at base it is possible to bot there at the moment. Is it possible to block 4-4 and 4-5. That he doesn´t use it as flee gate?**

to reproduce: 
bot on X-5, wait till it flees to 4-4 

expected:
that it at least jumps back on x-5 to continue shooting NPC but not that it waits 2 hours on 4-4 till someone comes along to kill it. 

My solution:
Maybe its better when the bot is not fleeing to 4-4 because on the other side he cant jump back if the enemie follows and attacks. The same should count for 4-5

**Comment by crashblaster** [comment]
Should be fixed with new update: v4.0.18.8-1: DO: Won't flee to 4-4

**Comment by crashblaster** [comment]
Bot still fleeing on 4-4:
09:55:50 [info] Threat recognized --THOR--
09:55:50 [info] Enemy '--THOR--' in sight.
09:55:50 [info] Jumping ...
09:55:54 [info] Connected to the Gameserver.
09:55:59 [info] Connection successfully established.
09:55:59 [info] Map '4-4'. id=16, width=42000, height=26200, previous map: '-2'
09:55:59 [info] Worker ready
09:56:00 [info] Hero ship data found
09:56:00 [info] Pressing After flee button(s)

Stucks there after jumping on 4-4

**Comment by berkeleyinc** [comment]
fixed with 4.19
