### ISSUE TITLE
Bot not using Flee Config 2 when there is an enemie in sight while changing workmap

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#75]
**Describe the bug**
Bot doesn´t change to flee config 2 when he gets shoot from an enemie and the bot tries to change the workmap at the same time. 

**To Reproduce**
Start NPC Killer. Wait for an enemie. Sometimes this issue happens. 
_I think the issue is happening because of this setting: 
Change workMap when: seeing an enemy_
As you can see in the log:
1:04:34 [info] Threat recognized AIANTAS
**01:04:34 [info] Changing WorkMap.**
01:04:34 [info] Calculated path from 3-8 to 3-7: 3-7
**01:04:34 [info] Pressing Flee button(s)**
01:04:50 [info] Ship has been destroyed. Reviving ship.

**Expected behavior**
The Bot should first flee to closest gate when there is an enemie in sight.
When the bot fleed succesfully he can switch the workmap. 

It should be changed to >> Change workMap when fleed succesfully from an enemie. Because the Bot isn´t using Config 2 (Flee Config) to get to the other map. The Bot should first flee from the enemie to closest gate and after that he can switch the workmap. Also the bot should switch to config 2 while changing workmap so the bot is faster and more efficient. The bot should first flee to the nearest gate instead of changing the workmap first as the path to the other workmap may be wider than the next gate. This also includes the switch Logic >> first flee button >> then switch to config 2 and also for the backswitch >> first config 1 then after flee button**

[log.txt](https://github.com/berkeleyinc/Golem/files/3061294/log.txt)

**Comment by berkeleyinc** [comment]
Fixed with v4.18.8
