### ISSUE TITLE
NPC Killer totaly bugged

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#76]
**Describe the bug**
Bot isnt attacking NPC´s anymore.

**To Reproduce**
Start NPC Killer.

**Expected behavior**
Normaly attacking NPC´s like before.

**Logg**
21:04:41 [warning] Could not select '-=[ StreuneR ]=-', distance=353
21:04:41 [info] Moving closer to target (3364|1717 -> 3406|1367)
21:04:41 [warning] Could not select '-=[ StreuneR ]=-', distance=424
21:04:41 [info] Moving closer to target (3378|1606 -> 3355|2029)
21:04:41 [warning] Could not select '-=[ StreuneR ]=-', distance=308
21:04:41 [info] Moving closer to target (3374|1685 -> 3361|1377)
21:04:41 [warning] Could not select '-=[ StreuneR ]=-', distance=330
21:04:41 [info] Moving closer to target (3370|1634 -> 3323|1307)
21:04:42 [warning] Could not select '-=[ StreuneR ]=-', distance=415
21:04:42 [info] Moving closer to target (3354|1518 -> 3257|1114)
21:04:42 [warning] Could not select '-=[ StreuneR ]=-', distance=519
21:04:42 [info] Moving closer to target (3331|1416 -> 3451|1921)
21:04:42 [warning] Could not select '-=[ StreuneR ]=-', distance=436
21:04:42 [info] Moving closer to target (3348|1492 -> 3450|1915)
21:04:42 [warning] Could not select '-=[ StreuneR ]=-', distance=261

**Additional context**

**Comment by berkeleyinc** [comment]
fixed
