### ISSUE TITLE
Switching NPC´s while attacking one (happens random)

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#78]
**Describe the bug**
Bot is attacking the selected NPC for 1-2 seconds and then he is flying away roaming or switching to another NPC. 

**To Reproduce**
Use NPC Killer, wait a few minutes.
It happens by chance. I also think it only happens on the highest prio NPC from the list.

**only happens with activated function: only attack NPCs with full HPTs** << not the reason

**Expected behavior**
He should first kill the NPC before selecting a new npc or searching for another one. I think he sometimes forgets the focus on the new attacked npc if a new npcs spawns in range or a box is in range. It doesnt happen much often.

**Log**
00:49:10 [info] NPC '-=[ Kristallin ]=-' killed. **<< killed the last one**
00:49:10 [info] Select '-=[ Kristallin ]=-'. **<< select new one**
00:49:11 [info] Earned 12800 Cre. (total 13629100)
00:49:11 [info] Earned 16 Uri. (total 7734)
00:49:13 [info] Select '-=[ Kristallin ]=-'.
00:49:13 [info] Select '-=[ Kristallin ]=-'.
00:49:13 [info] Attack '-=[ Kristallin ]=-'. **<< attacked the new one**
00:49:16 [info] Select '-=[ Kristallon ]=-'. **<< switched 3 seconds later and flew away**
00:49:17 [info] Roaming map ...
00:49:20 [info] Collecting box type 2
00:49:22 [info] Roaming map ...
00:49:24 [info] Collecting box type 2
00:49:25 [info] Earned 500 Cre. (total 13629600)
00:49:27 [info] Roaming map ...
00:49:27 [info] Threat recognized CBS
00:49:30 [info] Roaming map ...

After he found another NPC he is continuing normally.

**Comment by berkeleyinc** [comment]
"Immediate attack" removed with 4.18.7

**Comment by crashblaster** [comment]
reopend cause still bugged // it only happens with activated: only attack NPCs with full HPTs

**Comment by crashblaster** [comment]
It only happens when there is coming a friendly ship or there is spawning another npc next to you.

**Comment by crashblaster** [comment]
looks fixed with 4.19 testing

**Comment by crashblaster** [comment]
Still bugged got it now with debug:
It just happens when you activate: only attack NPCs with full HPTs.

10:28:24 [info] Roaming map ...
10:28:27 [info] Roaming map ...
10:28:28 [trace] BB955 BB955 BB955 tick=322
10:28:30 [info] Select '..::{ Boss StreuneR }::..'.
10:28:32 [info] Roaming map ...
10:28:33 [trace] BB955 BB955 BB955 tick=151
10:28:35 [info] Select '..::{ Boss StreuneR }::..'.
10:28:36 [info] Attack '..::{ Boss StreuneR }::..'.
10:28:38 [trace] BB955 BB955 BB955 tick=347
10:28:41 [info] Select '-=[ StreuneR ]=-'.
10:28:42 [info] Roaming map ...
10:28:43 [trace] BB955 BB955 BB955 tick=213
10:28:45 [info] Roaming map ...
10:28:48 [trace] BB955 BB955 BB955 tick=127
10:28:49 [info] Roaming map ...
10:28:52 [debug] Ping status server
10:28:53 [trace] BB955 BB955 BB955 tick=125
10:28:57 [info] Select '-=[ StreuneR ]=-'.
10:28:57 [info] Attack '-=[ StreuneR ]=-'.
10:28:58 [trace] BB955 BB955 BB955 tick=283
10:28:59 [info] Going to shoot range...
10:29:00 [trace] BB955 BB998 BB955 tick=405
10:29:00 [trace] BB955 BB998 BB998 tick=255
10:29:00 [trace] BB998 BB998 BB998 tick=400
10:29:00 [info] NPC '-=[ StreuneR ]=-' killed.
10:29:01 [trace] BB998 BB955 BB998 tick=260
10:29:01 [trace] BB998 BB955 BB955 tick=270
10:29:01 [trace] BB955 BB955 BB955 tick=205
10:29:01 [info] Earned 12000 Cre. (total 114791100)

**Comment by crashblaster** [comment]
fixed
