### ISSUE TITLE
Switching back to config 1 while fleeing from enemie with config 2 because of new function: cancle fleeing

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#79]
**Describe the bug**
The bot is switching back to config 1 while fleeing in config 2because the bot thinks the enemie has already left. But for real, he is right next to you and attacks.

**To Reproduce**
Bot on map and wait for an enemie.

**Expected behavior**
The bot shouldn´t switch back to config 1 while fleeing. The bot assumes too fast that the opponent is already gone.
It happens only sometimes. I think the reason is because of the new function: Cancel fleeing because threat is gone. I think we should remove this or improve it.

Mabe the delay/check up between "Threat recognized ..." and "Cancle Fleeing because threat is gone" must be higher then 2 Seconds. ^^

Also the drone switch is bugged with this feature.
When the bot thinks the enemies has left and he is switching back to config 1 and pressing after flee button, the following could happen:
Enemie left >> Config 1 >> After flee Button >> right after the config and drone switch the enemie comes back >> bot trys to flee but he can just switch the config and the flee button can not be executed because the drone switch is still on cooldown.

After a drone switch it is on cooldown for 2-3 seconds. The after flee button happens normaly a little bit later then the config switch. I think millisecs. I dont understand why this could happen.

Is it possible to make a fixed task out of it?

Flee Button >> Config Switch to config 2 >> earliest change only possible after 5 seconds
after that you can switch back to config 1 and then press after flee button. If the bot recognizes the enemie to fast, the bot trys to switch back on config 2 but he cant press flee button, because after flee button is still 2-3 seconds on cooldown.

This should count always for changing workmap >> flying to workmap >> fleeing from enemie and stop botting. When the bot has changed to config 1 before he has to wait ALWAYS 5 seconds before he can switch back to config 2. The same cooldown counts for switching back to config 1.

The Bot should stop fleeing and start back working again, when the enemie wasn´t in sight for over 5 or more seoncds.

**Log**
01:07:50 [info] Attack '-=[ Kristallin ]=-'.
01:07:54 [info] Threat recognized ──══»™ŞеηţịηеĻ™«══──
01:07:56 [warning] Multiple enemy sightings in short time detected.
01:07:56 [info] Fleeing to closest gate...
01:07:56 [info] Pressing Flee button(s)
01:07:57 [info] Earned 12800 Cre. (total 16442700)
01:07:57 [info] Earned 16 Uri. (total 9428)
01:07:58 [info] Cancel fleeing because threat is gone.
01:07:58 [info] Pressing After flee button(s)
01:07:58 [info] Threat recognized ──══»™ŞеηţịηеĻ™«══──
01:08:00 [info] Threat recognized ──══»™ŞеηţịηеĻ™«══──
01:08:00 [info] Enemy '──══»™ŞеηţịηеĻ™«══──' in sight.
01:08:00 [info] Fleeing to closest gate...
01:08:00 [info] Pressing Flee button(s)
01:08:02 [info] Cancel fleeing because threat is gone.
01:08:02 [info] Pressing After flee button(s)
01:08:02 [info] Threat recognized ──══»™ŞеηţịηеĻ™«══──
01:08:04 [info] Fleeing to closest gate...
01:08:04 [warning] Enemy '──══»™ŞеηţịηеĻ™«══──' got too close!
01:08:04 [info] Pressing Flee button(s)
01:08:12 [info] Ship has been destroyed. Reviving ship.
As you can see in the logg, The enemie killed me, but the bot recognized multiple times that the enemie has left.

And look at this:
01:19:43 [info] Attack '-=[ Kristallin ]=-'.
01:19:47 [info] Threat recognized Obeeliix
01:19:49 [info] Threat recognized Obeeliix
01:19:49 [warning] Multiple enemy sightings in short time detected.
01:19:49 [info] Fleeing to closest gate...
01:19:49 [info] Pressing Flee button(s)
01:19:49 [info] Changing to config 2...
01:19:51 [info] Cancel fleeing because threat is gone.
01:19:51 [info] Threat recognized Obeeliix
01:19:53 [warning] Multiple enemy sightings in short time detected.
01:19:53 [info] Fleeing to closest gate...
01:19:56 [info] Cancel fleeing because threat is gone.
01:19:56 [info] Changing to config 1...
01:19:56 [info] Fleeing to closest gate...
01:19:56 [warning] Enemy 'Obeeliix' got too close!

I was always to close with my second account, but the bot changed back to config 1...

**Comment by berkeleyinc** [comment]
in v4.18.7, the bot will wait for 5 seconds after the enemy is gone to make sure it's safe

**Comment by crashblaster** [comment]
ok i will test tonight

**Comment by crashblaster** [comment]
i tested 5 times when i attack him or he is already close to gate he is fleeing and jumping, when i am far away and just cross him he is going back to work after 5 sec. Perfect work! :)

**Comment by crashblaster** [comment]
fixed and closed
