### ISSUE TITLE
Bot is really slow overall tick rate sucks, everything goes slow

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#80]
**Describe the bug**
Everytime when there are some enemies on screen the tick rate goes to 200+

**To Reproduce**
Run Task mode/NPC killer on x-3 map

**Expected behavior**
The bot should have a steady tick rate

**Screenshots**
![Desktop Screenshot 2019 04 11 - 16 38 15 03](https://user-images.githubusercontent.com/45576830/55966367-880e9a00-5c78-11e9-9d87-cd29f23877a9.png)
![Desktop Screenshot 2019 04 11 - 16 42 41 21](https://user-images.githubusercontent.com/45576830/55966510-d7ed6100-5c78-11e9-95c7-7520f6f86a58.png)

**Additional context**
I've seen other bots steady at 15/10 msec could golem also get this improvement

**Comment by BottingMarket** [comment]
Did some testing with the 64 bit version and 32 bit, above pictures are from 64 bit that version is much worse tick rate then 32 bit the tick rate of the 32 is really steady

![Desktop Screenshot 2019 04 11 - 16 46 50 77](https://user-images.githubusercontent.com/45576830/55966879-88f3fb80-5c79-11e9-9a58-82807ed29a77.png)

**Comment by berkeleyinc** [comment]
it depends on the amount of objects on the map.
It wont get better than what the changes of the last versions improved
