### ISSUE TITLE
Bot still collect boxes when npc health is under 40%

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#81]
**Describe the bug**
Bot still collect boxes when npc health is under 40%

**To Reproduce**
Enable npc killer and kill and collect.

**Expected behavior**
Bot should not collect boxes when npc health is under 40%

**Screenshots**
-

**Additional context**
Tought this feature was added in a update

**Comment by crashblaster** [comment]
i noticed that too, but it just doesn´t happen often. I think the bot has some general problems with several tasks at the same time.
