### ISSUE TITLE
Press key when attacking NPC X

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#83]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but this will improve the abilities of Cyborg ships etc. by alot

**Describe the solution you'd like**
When attacking X NPC press button X

**Describe alternatives you've considered**
Press button every x seconds but with this it will waste the ability sometimes on weak npc only want it used on big health npc's.

**Additional context**
-

**Comment by berkeleyinc** [comment]
added
