### ISSUE TITLE
GG bot won't jump in the next wave

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#84]
**Describe the bug**
When GG bot is activated it won't jump in the next wave

**To Reproduce**
Enable GG bot and Enable jump into next wave

**Expected behavior**
Ship should jump into next wave.

**Screenshots**
-

**Additional context**
[Golem Thomas.log](https://github.com/berkeleyinc/Golem/files/3076063/Golem.Thomas.log)

**Comment by berkeleyinc** [comment]
fixed with 4.19
