### ISSUE TITLE
Bot can't go to 2-2 when he is in 4-4 or higher

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#85]
**Describe the bug**
Bot can't go to 2-2 when he is in 4-4 or higher

**To Reproduce**
Set workmap to 2-2 and go to 2-5

**Expected behavior**
Bot should normally jump through the gates

**Screenshots**
-

**Additional context**
-

**Comment by crashblaster** [comment]
Is that a bug? I mean how should the bot react, when he gets shot while flyling to the workmap? Revive at gate/base/on point is defined in settings. But how often should he try to fly this way? 4-4 and 4-x has many hounters so you can die a lot. Probably it is better when the bot just changes workmaps in higher or lower dimension and not between them. When you select x-2 and x-7 as workmap the bot should inform you in the logg >> Workmap to far away, pls fly by your self. Eventually a fixed selection of the workmap would be better. You can only tag maps with a higher dimension at the same time and the same applies to the lower dimension.

**Comment by crashblaster** [comment]
I asked iNk and he told me that the bot is ignoring all 4-x portals. So the bot can´t jump between old and new starsystem.

**Comment by BottingMarket** [comment]
Reopened because bot still jumps the portal in x-2 map when Spaceball event is on

**Comment by crashblaster** [comment]
@BottingMarket you exchanged it you mean #73
