### ISSUE TITLE
When revived on x-8 base it won't stay there

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#87]
**Describe the bug**
When revived on x-8 base it won't stay there, it will flee to a gate instead.

**To Reproduce**
Workmap x-8 and revive ship on base.

**Expected behavior**
Bot should stay at base when hp is full it must return to x-8 map

**Screenshots**
-

**Additional context**
[Golem Nyxon.log](https://github.com/berkeleyinc/Golem/files/3092826/Golem.Nyxon.log)

**Comment by berkeleyinc** [comment]
added in 4.19.0 (14:57)
