### ISSUE TITLE
Bot doesn't start attacking sometimes

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#89]
**Describe the bug**
Bot is not attacking fast/correctly, it takes a long time before it attacks.

**To Reproduce**
Use GG bot in Alpha Gate

**Expected behavior**
Bot should instantly attack npc's

**Screenshots**
-

**Additional context**
Video: 
[GG Bot Attack is not working correctly.zip](https://github.com/berkeleyinc/Golem/files/3099309/GG.Bot.Attack.is.not.working.correctly.zip)

**Comment by crashblaster** [comment]
Is the reason possibly the range? Or the spamming attack?

**Comment by BottingMarket** [comment]
Fixed with latest version using function 3? need more testing tho

**Comment by crashblaster** [comment]
fixed Update v4.25

**Comment by crashblaster** [comment]
reopened cause of many reports on discord
