### ISSUE TITLE
Change Bot Modes

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#9]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be good if you could send a command to change the bot mode

**Additional context**
for example : send "botmode 1" in the cmd for Collector

**Comment by berkeleyinc** [comment]
The cmd.exe window is only temporarily and will be replaced with another GUI in future versions

**Comment by iNSOMNiA3D** [comment]
> 
> 
> The cmd.exe window is only temporarily and will be replaced with another GUI in future versions

Ok this is nice to hear
