### ISSUE TITLE
No need to deselect target when it's destroyed

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#90]
**Describe the bug**
No need to deselect target when it's destroyed

**To Reproduce**
Use NPC Killer

**Expected behavior**
Bot should not deselect npc's only when fleeing

**Screenshots**
-

**Additional context**
Here is the log:
23:02:48 [info] Select '-=[ Mordon ]=- α12'.
23:02:48 [info] Attack '-=[ Mordon ]=- α12'.
23:02:48 [info] Attack '-=[ Mordon ]=- α12'.
23:02:48 [info] Attack '-=[ Mordon ]=- α12'.
23:02:48 [info] Attack '-=[ Mordon ]=- α12'.
23:02:49 [info] Attack '-=[ Mordon ]=- α12'.
23:02:49 [info] NPC '-=[ Mordon ]=- α12' killed.
23:02:49 [info] Select '-=[ Mordon ]=- α12'.
23:02:49 [trace] BB968 BB968 BB968 tick=40
23:02:50 [info] Select '-=[ Mordon ]=- α12'.
23:02:50 [info] Attack '-=[ Mordon ]=- α12'.
23:02:50 [info] Earned 6400 Cre. (total 291200)
23:02:50 [info] Earned 8 Uri. (total 424)
23:02:50 [info] Attack '-=[ Mordon ]=- α12'.
23:02:51 [trace] BB968 BB1675 BB968 tick=40
23:02:51 [trace] Deselecting target.
23:02:51 [info] Select '-=[ Mordon ]=- α12'.
23:02:51 [info] Attack '-=[ Mordon ]=- α12'.
23:02:51 [trace] Deselecting target.
23:02:51 [trace] BB968 BB1675 BB1029 tick=40
23:02:52 [info] Select '-=[ Mordon ]=- α12'.
23:02:52 [info] Attack '-=[ Mordon ]=- α12'.
23:02:52 [info] Attack '-=[ Mordon ]=- α12'.
23:02:52 [info] NPC '-=[ Mordon ]=- α12' killed.
23:02:52 [info] Earned 6400 Cre. (total 297600)
23:02:52 [info] Earned 8 Uri. (total 432)
23:02:53 [trace] Deselecting target.
23:02:54 [trace] Deselecting target.
23:02:54 [trace] Deselecting target.
23:02:55 [trace] Deselecting target.
23:02:55 [info] Select '-=[ Mordon ]=- α12'.
23:02:55 [info] Select '-=[ Mordon ]=- α12'.
23:02:56 [info] Attack '-=[ Mordon ]=- α12'.
23:02:56 [info] Attack '-=[ Mordon ]=- α12'.
23:02:56 [info] Attack '-=[ Mordon ]=- α12'.

When 23:02:49 [info] NPC '-=[ Mordon ]=- α12' killed. is Killed
it shouldn't deselect

**Comment by crashblaster** [comment]
I can´t reproduce this bug on x-5-x-8. I will test on x-3.

**Comment by berkeleyinc** [comment]
Fixed with next version
