### ISSUE TITLE
Auto Restart when RAM is overloaded

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#94]
**Is your feature request related to a problem? Please describe.**
If the ram rises above 2000 then it laggs. The Bot can also freeze or crash.

The efficiency also suffers. On slower PC´s maybe much earlier. So a scale would be nice.

**Describe the solution you'd like**
The bot checks the current Ram workload.
If it is over the 2000 MB or the stated value >> flying to safe spot >> Restarting.

On a scale can be selected from when a reboot is to take place. For example.:1000 - 4000 MB

**Describe alternatives you've considered**
Or automatic restart, when reaching over 2500 MB.

**Sometimes the bot shows wrong RAM results. He is showing minus values.** << i hope it is just a visuel bug

Screenshot follows.

**Comment by BottingMarket** [comment]
Similair tread #82

**Comment by berkeleyinc** [comment]
See #82
