### ISSUE TITLE
Bot should fly to an safe gate after Login if repair is needed

### ISSUE THREAD

**Issue by crashblaster** [berkeleyinc/Golem#98]
**Is your feature request related to a problem? Please describe.**
Yes if the bot restarts because the connection was lost. The bot maybe are in the middle on a map and lost life from NPC´s. So the bot tries to repair but can´t finish the repair because he gets attacked from NPC´s.

**Describe the solution you'd like**
The bot should first fly to an safe gate after restart >> repair >> start botting.

If the bot has full HP/shield he can start immediately.

**Comment by berkeleyinc** [comment]
Added with next version
